name: shaperush_mobile
description: ShapeRush mobile app frontend (Flutter).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.16.0
  intl: ^0.19.0
  health: ^11.1.1
  image_picker: ^1.2.1
  camera: ^0.12.0+2
  share_plus: ^10.1.4
  screenshot: ^3.0.0
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/shaperush_bg.png
    - assets/images/shaperush_logo.png
    - assets/images/shaperush_logo_padded.png
    - assets/images/google_logo.png

flutter_launcher_icons:
  android: true
  web:
    generate: true
    background_color: "#FFFFFF"
    theme_color: "#8350F6"
  image_path: "assets/images/shaperush_logo_padded.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/shaperush_logo_padded.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/shaperush_logo_padded.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/shaperush_logo_padded.png
  web: true
